---

# Provision virtual machine example

- hosts: localhost
  connection: local
  gather_facts: false

  vars:
    azure_image: OpenLogic:CentOS:7.1:7.1.20150731
    azure_location: eastus
    azure_prefix: tj3
 
  vars_files:
    - secrets.yml

  tasks:

    - name: "erzeuge group"
      command: azure group create {{ azure_prefix }}-group -l {{ azure_location }}

    - name: "erzeuge master"
      command: azure vm create --nic-name {{ azure_prefix }}-nic --public-ip-name {{ azure_prefix }}-pip --image-urn {{ azure_image }} --admin-username azureuser --ssh-publickey-file ~/azure-key-pair.pub --location {{ azure_location }} --vnet-name {{ azure_prefix }}-vnet --vnet-address-prefix 10.0.0.0/24 --vnet-subnet-name {{ azure_prefix }}-subnet --vnet-subnet-address-prefix 10.0.0.0/27 --public-ip-domain-name {{ azure_prefix }}-master {{ azure_prefix }}-group {{ azure_prefix }}-master linux    

    - name: "add host to group"
      add_host: > 
        name={{ azure_prefix }}-master
        ansible_ssh_host={{ azure_prefix }}-master.eastus.cloudapp.azure.com
        ansible_ssh_port=22
        ansible_ssh_user=azureuser
        ansible_ssh_private_key_file=/home/ec2-user/azure-key-pair

- hosts: tj3-master
  remote_user: azureuser
  sudo: true
  vars:
    jenkins_dest: /opt/jenkins
    jenkins_lib: /var/lib/jenkins
    jenkins_port: 8080
    jenkins:
      deb:
        repo: 'deb http://pkg.jenkins-ci.org/debian binary/' # Jenkins repository
        dependencies: # Jenkins dependencies
          - 'openjdk-7-jre'
          - 'openjdk-7-jdk'
          - 'git'
          - 'curl'
      redhat:
        dependencies:
          - 'java'
          - 'git'
          - 'curl'
      cli_dest: '{{ jenkins_dest }}/jenkins-cli.jar' # Jenkins CLI destination
      updates_dest: '{{ jenkins_dest }}/updates_jenkins.json' # Jenkins updates file
 
  tasks:
 
#    - name: update all packages
#      command: yum -y update

    - name: update all packages
      yum: name=* state=latest
 
    - name: Install python-pycurl
      yum: name=python-pycurl state=installed

    - name: Import jenkins key
      rpm_key:
        key: https://jenkins-ci.org/redhat/jenkins-ci.org.key
        state: present
        validate_certs: no

    - name: Get jenkins repo for ansible
      get_url:
        url: http://pkg.jenkins-ci.org/redhat/jenkins.repo
        dest: /etc/yum.repos.d/jenkins.repo
        
    - name: Install RedHat dependencies
      yum: name={{ item }} state=installed
      with_items: jenkins.redhat.dependencies

    - name: Install Jenkins for RedHat
      yum: name=jenkins state=latest
      register: jenkins_install

    - name: Ensure jenkins is running
      service:
        name: jenkins
        state: started

    - name: Start jenkins on boot
      shell: chkconfig jenkins on

    - include: config.yml

    - include: cli.yml

    - include: plugins.yml
  
#gem install taskjuggler

